# render.yaml
services:
  - type: web
    name: sos-thomas
    env: python
    pythonVersion: 3.11
    region: oregon
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000 # Render utilisera cette variable pour le port